language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq git
    - sudo apt-get install -y doxygen graphviz pandoc
    - sudo pip install --upgrade pip
    - sudo apt-get install mkdocs -y
    - git clone https://github.com/oric-software/buildTestAndRelease.git
    - cd buildTestAndRelease/ && sh make.sh
    - cd ..    
    - echo Current branch ${TRAVIS_BRANCH}
after_success:
    - mkdir -p build/usr/share/man/
    - cp Makefile build/usr/src/sha1/
    - cp README.md build/usr/src/sha1/
    - cd build && tar -c * > ../sha1.tar && cd ..
    - gzip sha1.tar
    - mv sha1.tar.gz sha1.tgz
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then VERSION=`cat VERSION`; else VERSION=alpha; fi'
    - echo $VERSION
    - curl -X POST --data-binary '@sha1.tgz' "https://cdn.oric.org/publish.php?hash=$hash&path=/home/oricoujr/www/ftp/orix/dists/$VERSION/tgz/6502/sha1.tgz"    

